stages:
  - compile
  - test

compile:
  stage: compile
  script:
    - scala compile .
  artifacts:
    paths:
      - .scala-build/
  survey: false

test:
  stage: test
  script:
    - scala test .
  dependencies:
    - compile
  survey: false