stages:
  - compile
  - test

compile:
  stage: compile
  script:
    - scala compile . --server=false
  artifacts:
    paths:
      - .scala-build/

test:
  stage: test
  script:
    - scala test . --server=false
  dependencies:
    - compile